src/nscreg.Data/Entities/StatUnitSearchView.cs, src/nscreg.Server.Common/AutoMapperProfile.cs, src/nscreg.Server.Common/Services/StatUnit/ElasticService.cs, src/nscreg.Server.Common/Services/StatUnit/SearchService.cs
Remove RegionId field from StatUnitSearchView since we don't use this field anymore (since we removed AddressId/AsRegistered). Update mappings to use ActualAddressRegionId instead.
=> Remove RegionId field from StatUnitSearchView. Update mappings.

dbseed/create-db-structure.sql
Previous format caused error 'InternalError: too much recursion' when pasting into live mermaid editor https://mermaid.live/edit
=> [db] Fix mermaid too much recursion error 

app/src/app/getting-started/activity-standard/_components/CategoryStandardForm.tsx, app/src/app/getting-started/activity-standard/page.tsx
By using the Type Shorthands we avoid redefining supabase response types.
[See Supabase documentation for more information](https://supabase.com/docs/guides/api/rest/generating-types#type-shorthands)
=> [ui] Simplify prop type definition in CategoryStandardFormProps

app/src/app/getting-started/upload-custom-activity-standard-codes/UploadCustomActivitiesForm.tsx, app/src/app/getting-started/upload-custom-activity-standard-codes/actions.ts, app/src/app/getting-started/upload-custom-activity-standard-codes/page.tsx, app/src/app/getting-started/upload-legal-units/UploadLegalUnitsForm.tsx, app/src/app/getting-started/upload-legal-units/actions.ts, app/src/app/getting-started/upload-legal-units/page.tsx, app/src/app/getting-started/upload-regions/UploadRegionsForm.tsx, app/src/app/getting-started/upload-regions/actions.ts, app/src/app/getting-started/upload-regions/page.tsx, app/src/app/search/hooks/useFilter.ts, app/src/components/CommandPalette.tsx, app/src/components/ErrorBox.tsx, app/src/components/InfoBox.tsx, app/src/lib/database.types.ts
Some countries might have their own category standard codes in addition, or instead of the **NACE / ISIC** standard codes. This PR adds a new upload page where the user can upload custom category standard codes.
This PR also adds error feedback whenever file uploads fail so that the user will know what has gone wrong.
**Example:**
Uploading a legal units file in regions upload form results in this error:
=> Add new page for uploading custom activity category codes

app/src/app/page.tsx, app/src/app/search/api/route.ts, app/src/app/search/components/search-result-table.tsx, app/src/app/search/hooks/use-filter.ts
Display statistical unit tax_reg_id next to name. Also include region code next to region name and activity category code next to name in filter value view.
=> [ui] Add tax_reg_id in search result and improve filter UX

app/src/app/getting-started/summary/page.tsx
**Work:**
- Display number of custom categories configured
- Refactor summary page to reuse common _SummaryBlock_ component for reduced code duplication
=> [ui] Display custom category count on getting-started summary page

app/src/components/command-palette/command-palette-actions.ts, app/src/components/command-palette/command-palette.tsx
The command palette action will invoke rpc statistical_unit_refresh_now that in turn will refresh the view statistical_unit used by StatBus search
=> [ui] Add command palette action for refreshing materialized search view

app/src/app/search/page.tsx, app/src/components/command-palette/command-palette.tsx
New views _region_used_ and _activity_category_used_ return only regions and categories that are in use by our statistical units. This improves the UX when filtering search results because the user is not given a bunch of alternatives that yield no data.
=> [ui] Implement materialized views for region and category search filters

app/src/app/search/api/route.ts, app/src/app/search/components/search-result-table.tsx, app/src/app/search/components/search.tsx, app/src/app/search/hooks/use-filter.ts, app/src/app/search/page.tsx, app/src/lib/database.types.ts
The structure of the `statistical_unit` has been altered. Amongst the changes is the introduction of `unit_type` and `unit_id` which replaces the previous `legal_unit_id`. These changes has been made to support _establishments_ as well as _enterprises_ in addition to _legal units_.
This PR will update the typescript definitions which are generated from the DEV database via the Supabase CLI.
=> [ui] Fix stat_unit search after breaking api changes

app/src/app/search/hooks/use-filter.ts, app/src/app/search/page.tsx
This PR adds a new search filter for `unit_type`. This let's the user filter search results by _enterprises_, _legal_units_ and _establishments_
=> [ui] Add unit type filter to stat unit search

app/src/app/reports/drill-down-chart.tsx, app/src/app/reports/search-link.tsx, app/src/app/reports/statbus-chart.tsx, app/src/app/search/constants.ts, app/src/app/search/hooks/use-filter.ts
**The problem:**
The _/reports_ page gives the user a way to drill down in regions and categories, but there is no way to see the actual data that the graphs are based on. This is due to the fact that the reports are based on an aggregated, materialized view optimized for graphing purposes.
**Proposed solution:**
One way to let the user export the data from the reports page is to combine the _reports_ and _search_ page. When the user drill down on `regions` and `categories` we can compose a `{region, activity_category}` search filter and pass this filter to the _search_ page to get the statistical data from on the search page.
=> [ui] Display and export report / graph data

app/src/app/establishments/[id]/[...slug]/page.tsx, app/src/app/establishments/[id]/inspect/page.tsx, app/src/app/legal-units/[id]/[...slug]/page.tsx, app/src/app/legal-units/components/submission-feedback-debug-info.tsx, app/src/components/data-dump.tsx, app/src/components/statistical-unit-details-link-with-sub-path.tsx, app/src/components/statistical-unit-details-link.tsx, app/src/components/statistical-unit-details/details-page.tsx, app/src/components/statistical-unit-hierarchy/topology-item.tsx, app/src/components/statistical-unit-hierarchy/topology.tsx
Keep sub path when navigating between units in hierarchy to allow user to stay in one context while navigating organizations within the hierarchy.
For instance, when viewing the contact information of one establishment, it is good UX to keep the contact information tab active when switching to and from another establishment / legal unit.
=> [ui] Keep sub path when navigating between units in hierarchy

app/src/app/search/components/conditional-value-badge.tsx, app/src/app/search/components/options-filter.tsx, app/src/app/search/hooks/use-filter.ts, app/src/app/search/search.types.ts
This PR builds on the latest changes on statistical units search where each statistical unit type is given a separate icon and color. 
In this PR we colorize the selected filter values and we also display the unit type the same way we do in the search result. Example: "Legal Unit" not "legal_unit".
=> [ui] Colorize unit type filter and set human-readable values

app/src/app/search/hooks/use-filter.ts, app/src/components/statistical-unit-icon.tsx, app/tailwind.config.ts
By providing tailwind color aliases in taiwind config it makes it easier to control the color theme and colors are not spread around the code base.
=> [ui] Define tailwind color aliases for various unit types

app/src/app/reports/search-link.tsx, app/src/app/search/components/search-result-table.tsx, app/src/app/search/components/search.tsx, app/src/app/search/constants.ts, app/src/app/search/create-filters.ts, app/src/app/search/hooks/__tests__/use-search.test.ts, app/src/app/search/hooks/use-filter.ts, app/src/app/search/hooks/use-search.ts, app/src/app/search/hooks/use-updated-url-search-params.ts, app/src/app/search/page.tsx, app/src/app/search/search.types.ts
To let the user navigate to and from the search page / unit details page without resetting the search filter we persist all filters in the URL. This also has the benefit of making the search sharable so that our users can share their search with their co-workers.
Since the initial filters are now available from the URL the filter component can be rendered on the server initially which gives a more responsive feel to it.
This PR also does some changes to improve the type safety when setting filter and search query parameters.
=> [ui] Keep search filter state in URL search param

app/src/app/search/hooks/use-updated-url-search-params.ts
We do not want to create another history object on stack, but rather replace the existing one.
=> [ui] Call replaceState when setting search filter query params

app/src/app/search/api/route.ts, app/src/app/search/components/search-result-table.tsx, app/src/app/search/search.types.ts
This PR will expand the search result table with a column for employee count.
It also updates the api route returning search results to include all attributes of a statistical unit.
=> [ui] Display employee count in search result table

app/src/app/enterprises/[id]/@header/default.tsx, app/src/app/enterprises/[id]/@nav/default.tsx, app/src/app/enterprises/[id]/@topology/default.tsx, app/src/app/enterprises/[id]/[...slug]/page.tsx, app/src/app/enterprises/[id]/contact/page.tsx, app/src/app/enterprises/[id]/enterprise-requests.ts, app/src/app/enterprises/[id]/inspect/page.tsx, app/src/app/enterprises/[id]/layout.tsx, app/src/app/establishments/[id]/@header/default.tsx, app/src/app/establishments/[id]/@topology/default.tsx, app/src/app/establishments/[id]/page.tsx, app/src/app/legal-units/[id]/@header/default.tsx, app/src/app/legal-units/[id]/@topology/default.tsx, app/src/app/search/components/search-result-table.tsx, app/src/components/statistical-unit-details-link.tsx, app/src/components/statistical-unit-hierarchy/topology-item.tsx, app/src/components/statistical-unit-hierarchy/topology.tsx, app/src/components/statistical-unit-icon.tsx
**Work**
- Add routes for _enterprise_ details, like the existing _establishment_ and _legal unit_ detail pages.
- Display enterprise in topology
- Mark establishment and legal_unit if **primary**
=> [ui] Expand hierarchy view

app/src/app/enterprises/[id]/page.tsx, app/src/app/establishments/[id]/page.tsx, app/src/app/legal-units/[id]/page.tsx, app/src/components/statistical-unit-details/details-page-error.tsx
This PR also fixes the error thrown on statistical unit details page. Previously a _PostgrestError_ was rethrown whenever stat unit details fetch failed. This did not serialize on error page. Now we instead throw a new `Error`, passing the postgres error message as message and root cause.
=> [ui] Display error message, stack and digest whenever details page fail

app/src/app/search/hooks/use-search.ts
The regex `/(?<=^|\P{L})[\p{L}\p{N}]+(?=\P{L}|$)/gu` is not supported by Safari on iOS. This commit wrap the regex constructor in try/catch and fallback to classic word boundary pattern. This has the side effect that unicode chars will not work on iOS Safari.
=> [ui] Handle iOS bug where search page fail due to missing regex support

app/src/components/statistical-unit-hierarchy/topology-item.tsx, app/src/components/statistical-unit-hierarchy/topology.tsx
**Work:**
This fixes an issue where enterprise link was pointing to /enterprises/:primary-legal-unit-id. This was because all information about the enterprise was resolved from the primary legal unit. This PR adds a new hierarchy item prop ('id') that will be used for setting the statistical unit link correctly
=> [ui] Fix erroneous enterprise hierarchy item link

app/src/app/search/components/statistical-unit-table-header.tsx, app/src/app/search/components/statistical-unit-table-row.tsx
Feedback from test user group stated that activity and category code should be main information and name secondary. This PR address this feedback. It also creates a cleaner UI for statistical units with `invalid_codes` (issues with import). These are now visualized with a `Bug` symbol with the invalid codes available in a popover box.
=> [ui] Minor UI adjustments to search result

app/src/app/api/logger/route.ts, app/src/lib/client-logger.ts
Some logging meta info is provided under the hood by the server logger instance. Because of this, we can simplify the logging API route.
- Email of logged-in user is provided by the server logger
- URL is resolved from referer header in server logger. The location object can therefore be omitted from the logging API route.
=> [ui, refactor] Simplify logging API route

app/src/app/page.tsx, app/src/app/reports/search-link.tsx, app/src/app/search/filters/unit-type-search-filter.ts
**Work:**
- Update dashboard to show unit count by type (enterprise, legal units and establishments)
- Set default unit_type search filter to _enterprise_
=> [ui] Split statistical units count by unit type

app/src/app/api/reports/route.ts, app/src/app/reports/statbus-chart.tsx, app/src/app/reports/use-drill-down-data.tsx, app/src/app/time-context-provider.tsx, app/src/app/use-relative-periods.ts, app/src/components/time-context-selector.tsx
This PR will add time context support on the reports / drill-down page.
=> [ui] Implement Time Context for reports / drill-down page

app/src/app/layout.tsx, app/src/components/footer.tsx, app/src/components/navbar.tsx
**Issue:**
The login page shows full menu with actions only intended for authenticated users.
**Proposed Fix:**
- Navbar and footer actions such as command palette, link to search, link to reports are only available if there is a session.
- To verify a session, the footer and navbar server components are now made async (because it needs to retrieve the supabase session information). To prevent navbar and footer from blocking page render, these components are now wrapped in separate `Suspense` boundaries.
=> [ui] Restrict priveleged menu actions

app/src/app/search/components/conditional-filter.tsx, app/src/app/search/components/options-filter.tsx, app/src/app/search/components/search-bulk-action-button.tsx, app/src/components/time-context-selector.tsx
This PR corrects all imports of the `Command` component from `cmdk` to _Shadcn_ component `@/components/ui`.
=> [ui] Import Command component from @/components and not cmdk

app/src/app/search/search-filter-reducer.ts
Whenever I update a search filter, the pagination is stuck on whatever was the previous selected page. If the new search filter yields fewer search results than before, this can result in an search result page even if there are search results on lower page numbers.
Whenever I update a search filter I expect the pagination to be reset to page 1
Reset pagination page number when filter query is updated
=> [ui] Reset pagination page number whenever any search filter change

app/src/components/statistical-unit-details-link-with-sub-path.tsx, app/src/components/statistical-unit-details-link.tsx
- Fix issue with searchparams like 'unit_type=enterprise' persisting in the URL when navigating from the search page
=> [ui] Fix unintended preservation of searchparams
