statisticsnorway/statbus

doc/todo/wizard.md
This PR adds a section to the wizard on data resetting
=> [docs] Add wizard cleanup steps

app/src/app/page.tsx, app/src/app/search/api/route.ts, app/src/app/search/components/options-filter.tsx, app/src/app/search/components/reset-filter-button.tsx, app/src/app/search/components/search-result-table.tsx, app/src/app/search/components/search.tsx, app/src/app/search/components/table-toolbar.tsx, app/src/app/search/hooks/use-filter.ts, app/src/app/search/search.types.ts, app/src/lib/database.types.ts
**Goal:**
Let user search for hierarchical data such as sub categories and sub regions.
=> Improve stat unit search using ltree operators for regions and categories

app/src/app/login/actions.ts, app/src/app/login/page.tsx, app/src/app/search/components/table-toolbar.tsx
Use `useFormState` hook toghether with _NextJS server action_ to display auth errors on login page.
=> [ui] Add user feedback on failed login

app/src/app/getting-started/page.tsx, app/src/app/getting-started/summary/page.tsx, app/src/app/layout.tsx, app/src/app/login/page.tsx, app/src/app/page.tsx, app/src/app/search/components/search-result-table.tsx, app/src/app/search/components/search.tsx, app/src/app/search/page.tsx, app/src/components/navbar.tsx
**Work:**
- Add new page _/search_
- Add navbar link to _/search_
- Fix consistent naming of _StatBus_ on various pages
=> [ui] Refactor search page into separate page

app/src/app/search/page.tsx
Fix bad naming after refactoring search from _Home_ into separate _Search_ page.
=> [ui] Fix bad naming

app/src/app/getting-started/summary/page.tsx, app/src/app/page.tsx, app/src/app/search/page.tsx
Create first version of Dashboard page
=> [ui] Add first version Dashboard page

app/src/app/search/api/route.ts, app/src/app/search/components/search-export-csv-link.tsx, app/src/app/search/components/search.tsx, app/src/app/search/export/route.ts, app/src/app/search/hooks/use-search.ts, app/src/app/search/page.tsx, app/src/app/search/search-requests.ts, app/src/components/command-palette/command-palette-trigger-button.tsx, app/src/components/command-palette/command-palette.tsx, app/src/components/navbar.tsx, app/src/lib/csv-utils.ts
This PR will add functionality for exporting search results as _.csv_ file. It also adds a _CommandPaletteTriggerButton_ component in the navbar, to help users identify the **⌘ + Shift + K** command.
=> [ui] Add statistical unit search CSV export

app/src/app/search/components/conditional-filter.tsx, app/src/app/search/components/options-filter.tsx, app/src/app/search/components/table-toolbar.tsx, app/src/app/search/hooks/use-filter.ts, app/src/app/search/search.types.ts, app/src/components/command-palette/command-palette-trigger-button.tsx, app/src/components/navbar.tsx
This PR fixes bug where user is not allowed to enter free text search with white space.
=> [ui] Fix bug where stat unit text search do not allow space

app/src/app/search/components/reset-filter-button.tsx, app/src/app/search/components/search-export-csv-link.tsx, app/src/app/search/components/search-save-button.tsx, app/src/app/search/components/search.tsx
**Work:**
- Update UI for `reset-filter-button` and `search-export-csv-link` components for more consistent icon button look
- Add UI element `search-save-button`
=> [ui] Add placeholder search filter save button

app/src/app/page.tsx, app/src/app/search/components/options-filter.tsx, app/src/app/search/create-filters.ts, app/src/app/search/hooks/use-search.ts, app/src/app/search/hooks/use-updated-url-search-params.ts, app/src/app/search/search.types.ts
Add search filter for listing statistical units that are missing primary activity category
=> [ui] Add null filter option for activity category and region

app/src/app/reports/bread-crumb.tsx, app/src/app/reports/drill-down-chart.tsx, app/src/app/reports/page.tsx, app/src/app/reports/statbus-chart.tsx, app/src/components/navbar.tsx
This PR builds on the [PR](https://github.com/statisticsnorway/statbus/pull/178) by @eriksoeb
=> [ui] Update chart look and feel

app/public/sector_norway.csv, app/src/app/getting-started/getting-started-actions.ts, app/src/app/getting-started/upload-csv-form.tsx, app/src/app/getting-started/upload-custom-activity-standard-codes/page.tsx, app/src/app/getting-started/upload-custom-sectors/page.tsx, app/src/app/getting-started/upload-regions/page.tsx, app/src/app/search/components/conditional-filter.tsx, app/src/app/search/components/conditional-value-badge.tsx, app/src/app/search/components/statistical-unit-table-header.tsx, app/src/app/search/components/statistical-unit-table-row.tsx, app/src/app/search/components/table-toolbar.tsx, app/src/app/search/create-filters.ts, app/src/app/search/hooks/__tests__/use-search.test.ts, app/src/app/search/hooks/use-search.ts, app/src/app/search/hooks/use-updated-url-search-params.ts, app/src/app/search/page.tsx, app/src/app/search/search-filter-reducer.ts, app/src/app/search/search.d.ts, app/src/components/command-palette/command-palette-actions.ts, app/src/components/command-palette/command-palette.tsx, app/src/components/ui/card.tsx, app/src/components/ui/dialog.tsx, app/src/components/ui/label.tsx
**Goal:**
This PR will add functionality for filtering search result based on sector codes. Example of sector codes are:
- _1510 Public unincorporated enterprises, owned by local government_
- _1120 Public incorporated enterprises, owned by central government_
- _1110 Public unincorporated enterprises, owned by central government_
**Work:**
=> [ui] Add sector search filter

app/src/app/getting-started/@progress/default.tsx, app/src/app/getting-started/@progress/nav-item.tsx, app/src/app/getting-started/activity-standard/category-standard-form.tsx, app/src/app/getting-started/getting-started-actions.ts, app/src/app/getting-started/layout.tsx, app/src/app/getting-started/summary/page.tsx, app/src/app/getting-started/upload-csv-form.tsx, app/src/app/getting-started/upload-custom-activity-standard-codes/page.tsx, app/src/app/getting-started/upload-custom-sectors/page.tsx, app/src/app/getting-started/upload-establishments/page.tsx, app/src/app/getting-started/upload-legal-units/page.tsx, app/src/app/getting-started/upload-regions/page.tsx, app/src/components/info-box.tsx
This PR will add a named slot `/getting-started/@progress` that will be included on all _getting-started_ pages. This slot will display the setup status on each step.
=> [ui] Add slot for setup / getting started status

app/src/app/search/components/options-filter.tsx
Add value prop in CommandItem to fix search in options filter
=> Fix bug in search for options filter

app/src/app/search/components/bulk-actions/combine-units.tsx, app/src/app/search/components/search-bulk-action-button.tsx, app/src/app/search/components/statistical-unit-table-row.tsx
=> [ui] Extract combine-units from search-bulk-action-button

app/src/app/globals.css, app/src/app/reports/drill-down-chart.tsx, app/src/app/search/components/conditional-filter.tsx, app/src/app/search/components/options-filter.tsx, app/src/app/search/components/reset-filter-button.tsx, app/src/app/search/components/search.tsx, app/src/app/search/components/statistical-unit-table-header.tsx, app/src/app/search/components/statistical-unit-table-row.tsx, app/src/app/search/components/table-toolbar.tsx, app/src/app/search/filters/full-text-search-filter.ts, app/src/app/search/page.tsx, app/src/components/command-palette/command-palette-trigger-button.tsx, app/src/components/command-palette/command-palette.tsx, app/src/components/navbar.tsx
=> [ui] Mak UI adjustments for mobile / tablet devices

app/src/app/establishments/[id]/page.tsx, app/src/app/establishments/[id]/update-establishment-server-actions.ts, app/src/app/legal-units/[id]/contact/contact-info-form.tsx, app/src/app/legal-units/[id]/general-info/general-info-form.tsx, app/src/app/legal-units/[id]/page.tsx, app/src/app/legal-units/[id]/update-legal-unit-server-actions.ts
> Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".
Extract legal unit set-primary server-action to separate server-actions file marked with "use server"
=> [ui, fixup] Fix server render error on unit details page

app/src/app/dashboard/page.tsx, app/src/app/search/components/search-result-pagination.tsx, app/src/app/search/components/search-result-table-row-dropdown-menu.tsx, app/src/components/footer.tsx, app/src/components/profile-avatar.tsx, app/src/components/ssb-logo.tsx
This PR addresses a11y issues on _start / dashboard page_ and _search page_ reported by [Lighthouse](https://chromewebstore.google.com/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk)
=> Improve accessibility

app/README.md, app/src/app/global-error-reporter.tsx, app/src/app/layout.tsx, app/src/app/login/actions.ts, app/src/app/search/components/search-result-table-body-skeleton.tsx, app/src/app/search/components/search-result-table.tsx, app/src/app/search/components/statistical-unit-table-row.tsx
=> [ui] Add general improvements

app/src/app/reports/drill-down-chart.tsx, app/src/app/reports/statbus-chart.tsx
… to improve visibility of small bars in drilldown chart
=> [ui] Add y-axis title and set minPointLength
